name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          workspace_json=$(xcodebuild -list -json | tr -d "\n")
          workspace=$(echo $workspace_json | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['name']")
          schemes=$(echo $workspace_json | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['schemes']")
          echo $workspace | cat >workspace
          echo $schemes | cat >schemes
          echo Building schemes: $schemes
      - name: Build
        run: |
          workspace=`cat workspace`
          schemes=`cat schemes`
          for scheme in $scheme; do
            xcodebuild clean build analyze -workspace "$workspace" -scheme "$scheme" | xcpretty && exit ${PIPESTATUS[0]}
          done
