name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          workspace_json=$(xcodebuild -list -json | tr -d "\n")
          workspace=$(echo $workspace_json | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['name']")
          schemes=$(echo $workspace_json | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['schemes']")
          echo $workspace | cat >workspace
          echo $schemes | cat >schemes
          echo Prepared schemes of $workspace.workspace: $schemes
      - name: Build
        run: |
          workspace=`cat workspace`
          schemes=`cat schemes`
          for scheme in $schemes; do
            echo Building $scheme scheme of $workspace.workspace
            set -o pipefail && xcodebuild build test -workspace "$workspace.xcworkspace" -scheme "$scheme" -destination 'platform=iOS Simulator,name=iPhone 8' -enableCodeCoverage YES | xcpretty
          done
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
